# Generated by Django 4.1.3 on 2023-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jpy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
