# Generated by Django 4.1.3 on 2023-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(help_text='Date when quotation was generated'),
        ),
    ]
