# Generated by Django 4.1.3 on 2023-12-21 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
